# Generated by Django 3.2.10 on 2022-01-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wilaya',
            name='price',
        ),
        migrations.AddField(
            model_name='wilaya',
            name='home_delivery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Livraison à domicile'),
        ),
        migrations.AddField(
            model_name='wilaya',
            name='relai_delivery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Livraison point de Relais'),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='mat',
            field=models.IntegerField(blank=True, null=True, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Wilaya'),
        ),
    ]
