# Generated by Django 3.2.10 on 2021-12-20 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20211220_1100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photos',
        ),
    ]
