# Generated by Django 3.2.10 on 2021-12-20 14:17

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_category_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('order'), nulls_last=True)], 'verbose_name': 'Produit', 'verbose_name_plural': '3. Produits'},
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='ordre'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Stock initial'),
        ),
        migrations.AddField(
            model_name='product',
            name='to_home_page',
            field=models.BooleanField(default=False, verbose_name="Affiché dans la page d'accueil"),
        ),
    ]
