# Generated by Django 3.2.10 on 2021-12-20 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20211220_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo10',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo7',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo8',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo9',
        ),
        migrations.CreateModel(
            name='PhotoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.ImageField(upload_to='images/produits')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.product')),
            ],
        ),
    ]
