# Generated by Django 3.2.10 on 2021-12-20 10:04

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'entreprise")),
                ('logo', models.ImageField(upload_to='images/logos', verbose_name='Logo')),
                ('logo_negatif', models.ImageField(upload_to='images/slides', verbose_name='Logo négatif')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Titre')),
                ('adress', models.CharField(blank=True, max_length=50, verbose_name='Adresse')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name="email de l'entreprise")),
                ('email2', models.EmailField(blank=True, max_length=50, verbose_name="2eme email de l'entreprise")),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name="numéro de téléphone de l'entreprise")),
                ('phone2', models.CharField(blank=True, max_length=50, verbose_name="2eme numéro de téléphone de l'entreprise")),
                ('about', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text a propos')),
                ('mini_about', models.TextField(blank=True, null=True, verbose_name="Petit texte a propos de l'entreprise ( bas de page)")),
                ('about_photo', models.ImageField(blank=True, null=True, upload_to='slides/', verbose_name='Photo A propos 440 X 275 px')),
                ('facebook', models.URLField(blank=True, max_length=300, null=True, verbose_name='Lien page Facebook')),
                ('insta', models.URLField(blank=True, max_length=300, null=True, verbose_name='Lien page Instagram')),
                ('twitter', models.URLField(blank=True, max_length=300, null=True, verbose_name='Lien Compte Twitter')),
                ('google_plus', models.URLField(blank=True, max_length=300, null=True, verbose_name='Lien Compte Google plus')),
                ('youtube', models.URLField(blank=True, max_length=300, null=True, verbose_name='Lien Chaine Youtube')),
                ('chat_code', models.TextField(blank=True, null=True, verbose_name='Script messagerie instantané')),
                ('pixel', models.TextField(blank=True, null=True, verbose_name='Script Facebook pixel')),
                ('analytics', models.TextField(blank=True, null=True, verbose_name='Script Analytics')),
                ('contact_message', models.TextField(blank=True, null=True, verbose_name='Contact message')),
                ('google_maps', models.TextField(blank=True, null=True, verbose_name='iframe google maps')),
            ],
            options={
                'verbose_name': ' Infomation',
                'verbose_name_plural': ' Infomations',
            },
        ),
    ]
