# Generated by Django 3.2.10 on 2021-12-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='is_big',
            field=models.BooleanField(default=False, verbose_name='Grande photo Home (1920 x 570) / About (1900 x 240)'),
        ),
    ]
